name: Slides

on:
  push:
    branches: [main]
    paths:
      - src/**

jobs:
  build_latex:
    runs-on: ubuntu-20.04

    steps:
      - name: Partial Clone
        shell: bash
        run: |
          REPO="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          git clone -q --filter=blob:none --no-checkout --depth=1  --sparse $REPO .
          git sparse-checkout init --cone
          git sparse-checkout set src
          git checkout

      - uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ghcr.io
          image: ghcr.io/cpp-review-dune/introductory-review/aur:latest
          options: |
            -v ${{github.workspace}}:/work
          shell: bash
          run: |
            yay -Syyuq --needed --noconfirm
            yay -S texlive-latexextra texlive-pictures texlive-science texlive-fontsextra texlive-bibtexextra biber gnu-free-fonts inkscape minted ttf-fira-code cmake --noconfirm
            export PATH="/usr/bin/vendor_perl:$PATH"
            sudo chown -R builder:builder /work && pushd /work/src && arara beamer && popd
            mkdir -p public && mv src/beamer.pdf public
            mv public/beamer.pdf public/slides.pdf

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
